name: masters_project_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.4.15
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
  llama_sdk: ^0.0.5
  path: ^1.9.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  sqflite: ^2.4.2
  ulid: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
